### ISSUE TITLE
Release artifacts should include a binary

### ISSUE THREAD

**Issue by mattymo** [kubernetes-sigs/etcdadm#100]
etcdadm should release binaries like other projects do. It shouldn't be mandatory to install from source. It takes ~2 minutes on most platforms to install golang and run `go get -u sigs.k8s.io/etcdadm`, while downloading the resulting tarball would take ~10 seconds.

**Comment by dlipovetsky** [comment]
Good point!

**Comment by moshloop** [comment]
https://goreleaser.com looks like it is the best option for this -  I am happy to submit a PR for it, just need to confirm a few details:

Build job hosting: I have used TravisCI + Github API Token successfully before
Binary names:  The default is `etcdadm_1.0_linux_amd64` - however this isn't very script/installation friendly - I think etcdadm, etcdadm.exe and etcdadm_osx are nicer.

**Comment by moshloop** [comment]
@dlipovetsky  for an example of what goreleaser would look like:  

https://github.com/moshloop/configadm/releases

I added a script in addition to goreleaser to upload binaries and archives.

**Comment by MarkusTeufelberger** [comment]
Yes, please add some binaries, it would be awesome to add etcdadm to Kubespray as _the_ method to install standalone etcd clusters.

**Comment by dlipovetsky** [comment]
Thanks to #103, the next release will have binary artifacts! When that happens, I'll close this issue.

**Comment by MarkusTeufelberger** [comment]
/remove-lifecycle rotten

Still an issue, still no release for over half a year.

**Comment by MarkusTeufelberger** [comment]
/remove-lifecycle stale

And still no release with a binary...
