### ISSUE TITLE
Getting context Deadline exceeded

### ISSUE THREAD

**Issue by abhijeetka** [kubernetes-sigs/etcdadm#102]
When I am trying to join a new machine to etcd cluster, I am getting following error.

`etcdadm join --log-level=debug  https://100.82.23.200:2379
INFO[0000] [certificates] creating PKI assets
INFO[0000] creating a self signed etcd CA certificate and key files
[certificates] Using the existing ca certificate and key.
INFO[0000] creating a new server certificate and key files for etcd
[certificates] Using the existing server certificate and key.
INFO[0000] creating a new certificate and key files for etcd peering
[certificates] Using the existing peer certificate and key.
INFO[0000] creating a new client certificate for the etcdctl
[certificates] Using the existing etcdctl-etcd-client certificate and key.
INFO[0000] creating a new client certificate for the apiserver calling etcd
[certificates] Using the existing apiserver-etcd-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/etcd/pki"
INFO[0000] [membership] Checking if this member was added
FATA[0005] [membership] Error checking membership: context deadline exceeded`

I am using CentOS 7.5 and Go 1.12 version

**Comment by dlipovetsky** [comment]
Thanks @abhijeetka.

etcdadm will this exit with this error if the etcd endpoint (in this case, `https://100.82.23.200:2379`) is does not reply to the API request in time (currently 5 seconds, not user-configurable: https://github.com/kubernetes-sigs/etcdadm/blob/e66ac180c7b21b37a58eeb5c40c0f8fbfd01d130/constants/constants.go#L42)

Though the outage might be temporary, etcdadm does not retry the request. Do you think a retry would help? There's a trade-off between failing fast and retrying. Do you know what the cause of the outage was in your case?

I think the error message could be more informative. I'll file an issue for that.

**Comment by hchenxa** [comment]
I got the same error and from the etcd bootstrap node, the message shows like:
```
May 23 19:32:39 chen2.fyre.ibm.com etcd[28589]: rejected connection from "172.16.218.104:47842" (error "remote error: tls: bad certificate", ServerName "")
May 23 19:34:32 chen2.fyre.ibm.com etcd[28589]: rejected connection from "172.16.218.104:47844" (error "remote error: tls: bad certificate", ServerName "")
May 23 19:34:33 chen2.fyre.ibm.com etcd[28589]: rejected connection from "172.16.218.104:47846" (error "remote error: tls: bad certificate", ServerName "")
May 23 19:34:34 chen2.fyre.ibm.com etcd[28589]: rejected connection from "172.16.218.104:47848" (error "remote error: tls: bad certificate", ServerName "")
```
