### ISSUE TITLE
create a etcdadm versioned configuration format

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/etcdadm#108]
we discussed during the meeting of 24th of June 2019 that etcdadm needs a configuration format, that follows the Kuberentes API machinery.

https://docs.google.com/document/d/1b_J0oBvi9lL0gsPgTOrCw1Zlx3e7BYEuXnB3d2S15pA/edit#

this will allows us to mange differences between etcd version WRT to etcdctl flags and etcd API changes between releases.

the kubeadm etcd types can be used as a starting point.
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#ExternalEtcd
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#LocalEtcd

if anybody has ideas please add them in this ticket.

/priority important-soon
/kind feature

/assign @justinsb 
cc @mattymo

**Comment by xrmzju** [comment]
hi, i've implement a internal version etcdadm versioned config and works fine in our situation, i wrote a brief design doc for the implemention @dlipovetsky @justinsb would you mind take a look at this?(
https://docs.google.com/document/d/1zpztxZ3t7AjoXUrIefzbnqyVLATwATqrvFaRaR-8Xm8)

**Comment by dlipovetsky** [comment]
Thanks, @xrmzju . I'll take a look soon.
