### ISSUE TITLE
Tide is failing to merge PRs in this repo because the GH settings conflict with Tide's settings.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/etcdadm#112]
See: https://prow.k8s.io/tide-history?repo=kubernetes-sigs%2Fetcdadm&branch=master&state=failure

> Tide needs to be configured to use the 'rebase' merge method for this repo or the repo needs to allow merge commits: Merge commits are not allowed on this repository.

Please either:
- PR a fix to the Tide configuration here: https://github.com/kubernetes/test-infra/blob/9adb196811caa99072e34fcb1489924bb57ef0ce/prow/config.yaml#L434-L456

OR
- Have a repo admin fix the GitHub settings for the repo.

Tide will fail to merge PRs in this repo and waste API rate limit until this is fixed.

**Comment by cjwagner** [comment]
From root OWNERS:
/assign @justinsb @dlipovetsky

**Comment by neolit123** [comment]
@cblecker, @nikhita are you able to adjust the settings of this repo?

**Comment by cblecker** [comment]
I've enabled merge commits on the repo from the settings panel. If this is fine with the repo admins, this may be closed. If you'd prefer tide to use merge commits, then we should change this in the tide config.

**Comment by neolit123** [comment]
thanks, i'm +1 on closing but will defer to @justinsb and @dlipovetsky

**Comment by justinsb** [comment]
Thanks for fixing @cblecker 

This feels like something that should be consistent across all the k* repos.  Tagging for contrib-x and will add to their agenda.

**Comment by cblecker** [comment]
The default is our consistency (use merge commits). Some repos specifically desire (for one reason or another) to use a non-default setting.

You are currently on the default setting. If everything is good, then feel free to close this.
