### ISSUE TITLE
MemoryLow not support in cgroup v1

### ISSUE THREAD

**Issue by pytimer** [kubernetes-sigs/etcdadm#114]
**Environment**:
- **etcdadm version**:

I use `go get -u sigs.k8s.io/etcdadm` to generate etcdadm binary.

```sh
version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
```
- **OS** (e.g. from /etc/os-release):

```sh
CentOS Linux release 7.6.1810 (Core)
```

```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. from `uname -a`):

`Linux host-10-33-41-128 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I use `etcdadm` to create etcd ha cluster in my host, it init successfully. and i run `etcdctl.sh` to check endpoints health, it healthy. But i see the etcd systemd have error log.

```sh
systemd[1]: [/etc/systemd/system/etcd.service:20] Unknown lvalue 'MemoryLow' in section 'Service'
```

I find the document write `Currently tested on Container Linux, with plans for other platforms.`, so i think maybe my problem is not a bug, but i want to ask that could etcdadm detect cgroup version and then decide wether add MemoryLow paramter in systemd service?

**Comment by dlipovetsky** [comment]
Thanks for reporting this!

Two things come to mind:
1. etcdadm should specify the version of systemd it requires. (I believe the version is older on CentOS 7.x than on Container Linux stable or Ubuntu 18.04 LTS. I'll check.)

2. It would be good for etcdadm to know when systemd reports an issue. Not sure that's possible.

**Comment by pytimer** [comment]
> etcdadm should specify the version of systemd it requires.

I hope the etcdadm can support the version of CentOS 7.x systemd, because kubernetes support it, i can use etcdadm create ha cluster if etcdadm support, so i hope the etcdadm can support.

> It would be good for etcdadm to know when systemd reports an issue. Not sure that's possible.

I am not understand it, if you have time, can you tell me detailed?

**Comment by dlipovetsky** [comment]
@pytimer  Sorry that my comment wasn't clear. 

- etcdadm _should_ support CentOS 7.x
- I think you report that it _does_ support CentOS 7.x (but systemd complains about the `MemoryLow` property)
- etcdadm should document which systemd version(s) it supports
- etcdadm should make adjustments for some versions, if necessary (e.g. removing the `MemoryLow` property).

**Comment by pytimer** [comment]
@dlipovetsky Thanks for you reply.

I understand. Thanks again. :-)
