### ISSUE TITLE
Support etcd lifecycle (deploy / upgrade) as static pods

### ISSUE THREAD

**Issue by johnharris85** [kubernetes-sigs/etcdadm#117]
Currently etcdadm supports etcd as a systemd service, but it would be great to support deploying etcd as static pods in the same way that kubeadm currently does. This isn't a trivial undertaking, but we could leverage a lot of existing work in kubeadm once the underlying implementation has been abstracted.

There are a couple of main benefits to this:
- kubeadm already works in this way (consistent approach / knowledge / interface)
- Running as static pods allows easier support for OS / platforms (e.g., LinuxKit, Talos) that don't include systemd but do bundle / or make it easier to install kubelet

**Comment by dlipovetsky** [comment]
Thanks for bringing this up at the meeting @johnharris85!

/kind feature
/priority important/long-term

**Comment by fabriziopandini** [comment]
+1 to this request from my side.

**Comment by xrmzju** [comment]
is there any body working on this? if not, i'am willing to help with it.

**Comment by neolit123** [comment]
AFAIK nobody is working on this currently @xrmzju 
but it might be a good idea, before sending PRs to share your ideas in a document - i.e. how you are planning to approach the static pod support?
