### ISSUE TITLE
RFE: certs subcommand to aid in copy/pasta CA certs

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/etcdadm#125]
Maybe I missed it but etcdadm just told me to 

```
INFO[0005] To add another member to the cluster, copy the CA cert/key to its certificate dir and run: 
INFO[0005] 	etcdadm join https://10.0.0.19:2379 
```

But I didn't see any commands that would help me achieve this task. It might be nice to have a command to tar up the certs or at least provide me with some bash i can copy paste.

**Comment by CamelCaseNotation** [comment]
+1 agree, I actually just opened an issue but this is pretty much what I want

**Comment by chuckha** [comment]
The command is in the readme: https://github.com/kubernetes-sigs/etcdadm#adding-a-member

but it would be nice to print it out in the command

**Comment by boluisa** [comment]
happy to take this one :)

**Comment by dlipovetsky** [comment]
/assign @boluisa 

Thanks!
