### ISSUE TITLE
Surprising output of `etcdadm reset`

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/etcdadm#126]
etcdadm refused to reset my node because it was the last member in the cluster. However, I ran the command again and everything seemed to be deleted properly:

```
root@ip-10-0-0-49:~# ./go/bin/etcdadm reset
INFO[0000] [reset] etcd service is running              
INFO[0000] [membership] Checking if this member was removed 
INFO[0000] [membership] Member was not removed          
INFO[0000] [membership] Not removing member because it is the last in the cluster 
INFO[0001] [cluster] etcd reset complete                

# Followed by

root@ip-10-0-0-49:~# ./go/bin/etcdadm reset
INFO[0000] [reset] etcd service is not running          
INFO[0000] [membership] Assuming that the member was removed 
INFO[0000] remove /etc/systemd/system/etcd.service: no such file or directory 
INFO[0000] remove /etc/etcd/etcd.env: no such file or directory 
INFO[0000] remove /etc/etcd/etcdctl.env: no such file or directory 
INFO[0000] [binaries] Unable to uninstall binaries: remove /opt/bin/etcd: no such file or directory 
INFO[0000] remove /opt/bin/etcdctl.sh: no such file or directory 
INFO[0000] [cluster] etcd reset complete                
```

I didn't see a `--force` flag for `reset` that should allow me to delete the last member but it appears to have done so anyway after running it twice.

**Comment by pytimer** [comment]
If current node is the last member, it doesn't need to remove this member from the cluster. Any data will deleted after etcdadm reset on the last member.

**Comment by chuckha** [comment]
The surprising part is that I ran the same command twice and got different results each time

**Comment by dlipovetsky** [comment]
I think we could make the two phases of leaving (remove member, stop etcd) and joining more clear in the output.

/priority important-longterm
