### ISSUE TITLE
Joining a third member fails (sometimes)

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/etcdadm#133]
There appears to be a health check of the cluster when joining a node. If you join two nodes in quick succession the second one will fail since the cluster takes a second to get healthy for a third node to join

I recommend adding a retry with backoffs of 1, 3, 5 seconds which would cap the total wait time to 9 seconds for joining a node.

/kind bug

**Comment by pytimer** [comment]
@chuckha I add exponential backoff retry for join member, i already testing add two members at the same time  in my environment, it works. You can review and test it if you have time.
