### ISSUE TITLE
info should print the version

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/etcdadm#135]
this might be out of scope since it's easy enough to get with etcdctl but should the info subcommand print the etcd version?

feel free to close this if it's out of scope.

**Comment by pytimer** [comment]
@chuckha I have two ways to show etcd member hex ids, which way do you think better or you have other idea ?

1. `etcdctl` show memberIDs in hex when `--write-out=simple`, if `etcdadm info` wants similar to it,  `etcdadm info` command add  `--output` flag, such as `etcdadm info --output=json/simple`.

2. Change this command print info, the output like below:

```json
{
  "ID": 15417523176468857193,
  "hexID": "d5f60ba4b9c74169",
  "name": "etcd-1",
  "peerURLs": [
    "https://192.168.10.100:2380"
  ],
  "clientURLs": [
    "https://192.168.10.100:2379"
  ]
}
```
