### ISSUE TITLE
builder: cannot find package "github.com/coreos/etcd/snapshot"

### ISSUE THREAD

**Issue by xistoso** [kubernetes-sigs/etcdadm#151]
I was just cheking out and trying to build:

> go get -u sigs.k8s.io/etcdadm

Go this error:

`package github.com/coreos/etcd/snapshot: cannot find package "github.com/coreos/etcd/snapshot" `

something must have change in etcd repo,
can you replicate?

**Comment by xistoso** [comment]
SO: ubuntu 19.10
Fresh install with:
apt-get install golang-go.tools

**Comment by neolit123** [comment]
i think the new path is go.etcd.io/etcd/clientv3/snapshot
or https://github.com/etcd-io/etcd/tree/master/clientv3/snapshot

**Comment by xistoso** [comment]
Later i'll find the etcd commit where that path changed. And write the pull request.
For now [commit](https://github.com/xistoso/etcdadm/commit/68e2eb547aa95bc4cbb3650890e69866ab0c2bb4) fixed it for me.

**Comment by neolit123** [comment]
>  And write the pull request.

ok, please do.

**Comment by xistoso** [comment]
@neolit123
I'm a bit lost. I'm new to Go. I understand your comments about the changed repo and drifted versioning tags. 
To fix for now we sould pin a specific version, example v3.4.3 but with the v0.0 hash. 
The problem is i don't know how to pin or require specific versions. I need to learn package management first.

PS: At least for now i've been able to fix my cluster ty for creating this amazing tool.

**Comment by neolit123** [comment]
commented here https://github.com/kubernetes-sigs/etcdadm/pull/152#issuecomment-585263943
