### ISSUE TITLE
GSoC Tracking Issue: Integrate with Cluster API to Support External Etcd Topology

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/etcdadm#153]
(Tracking issue for GSoC proposal)

Cluster API supports external etcd by adding kubeadm external etcd configuration inside `clusterConfiguration` field in `KubeadmConfig` directly. The limitation is Cluster API is unable to manage external etcd itself. This project aims to address that limitation by implementing a controlplane that uses etcdadm to manage the aspect of the external etcd cluster.

/cc @dlipovetsky

**Comment by neolit123** [comment]
would this work depend on https://github.com/kubernetes-sigs/etcdadm/issues/108 ?

**Comment by prksu** [comment]
I think this is not so dependent on that. we can still implement it but only limited to the etcdadm command with flags for the bootstrap provider. however, we would be better if we have versioned config like kubeadm and allows configuration through files.
I would be happy to implement versioned configuration. maybe I will think about it before GSoC starts.

**Comment by yashrsharma44** [comment]
Hey @prksu !
I saw this project idea on the potential community bridge project list, so can you provide some details about the project?
I would love to prepare a proposal and submit it for working on it!
