### ISSUE TITLE
unable to select an IP from default routes.

### ISSUE THREAD

**Issue by yinjun622** [kubernetes-sigs/etcdadm#155]
FATA[0000] [defaults] Error: failed to set default InitialAdvertisePeerURLs: failed to find a default external address: unable to select an IP from default routes.

**Comment by dlipovetsky** [comment]
@yinjun622 From what I recall, etcdadm uses the same algorithm as kubeadm to determine the address to advertise to peers. The address must be reachable from the peers. Are you able to work around this by providing an advertise URL, or do you have to rely on the defaulting?
