### ISSUE TITLE
`go get -u sigs.k8s.io/etcdadm` fails with module path error

### ISSUE THREAD

**Issue by scottslowe** [kubernetes-sigs/etcdadm#156]
I wanted to pull down `etcdadm` for some testing, and the `go get` command referenced in `README.md` under the "Building" section fails. Here's the final few lines of the output of the command:

```
...
go: github.com/xiang90/probing upgrade => v0.0.0-20190116061207-43a291ad63a2
go: github.com/ghodss/yaml upgrade => v1.0.0
go: k8s.io/client-go upgrade => v11.0.0+incompatible
go get: github.com/coreos/bbolt@v1.3.2 updating to
	github.com/coreos/bbolt@v1.3.4: parsing go.mod:
	module declares its path as: go.etcd.io/bbolt
	        but was required as: github.com/coreos/bbolt
```

This is on an Ubuntu 19.10 system with Go 1.14.1 installed.

How can I resolve this error so that I can test `etcdadm`?

**Comment by dlipovetsky** [comment]
Thanks for reporting @scottslowe. I think this is related to #58.

I took a quick look, but I don't think this is a quick fix.

I have no issues building `master` with go 1.12.14. We'll have binaries with the next release. Can you build with go 1.12.x for now?

**Comment by scottslowe** [comment]
@dlipovetsky Apologies for the newbie-ish question: are you saying that `go get` will work if I use Go 1.12.x? (I'm guessing this side-steps the module error.)

**Comment by scottslowe** [comment]
`go get` failed on my main system with Go 1.12.17, as well as on a fresh Ubuntu 18.04 build VM running Go 1.12.17 (both systems reported multiple errors during compilation). However, using `make` from within the repository seemed to work.

**Comment by dlipovetsky** [comment]
> `go get` failed on my main system with Go 1.12.17, as well as on a fresh Ubuntu 18.04 build VM running Go 1.12.17 (both systems reported multiple errors during compilation). However, using `make` from within the repository seemed to work.

Thanks a lot for checking that!

I'll need to investigate the cause. But for now, I'd like to PR a doc change, to replace `go get` with `git clone` followed by `make etcdadm`.  WDYT?

FWIW, I've come across hard-to-understand issues with `go get` in other projects recently.

**Comment by scottslowe** [comment]
> But for now, I'd like to PR a doc change, to replace `go get` with `git clone` followed by `make etcdadm`. WDYT?

Seems reasonable to me. Thanks! Let me know if there is additional testing I can do that would be helpful.

**Comment by scottslowe** [comment]
@dlipovetsky Would you like me to PR the suggested doc change?

**Comment by dlipovetsky** [comment]
@scottslowe I'm sorry, I just saw your comment! I PR'd the change myself a little while ago. I'll keep this issue open to look into the `go get` issue.

**Comment by justinsb** [comment]
I propose once https://github.com/etcd-io/etcd/pull/11823/files lands, that we move our import to be go.etcd.io/etcd, which has support for go.mod and I hope will fix this issue.

AFAICT we only use the etcd client libraries, so this shouldn't cause problems.
