### ISSUE TITLE
How to specify the version of etcd for installation

### ISSUE THREAD

**Issue by lemonit-eric-mao** [kubernetes-sigs/etcdadm#167]
use etcdadm  How to specify the version of etcd for installation

**Comment by dlipovetsky** [comment]
@lemonit-eric-mao This is a great question for the #etcdadm channel on the [Kubernetes slack instance](slack.k8s.io).

You can specify the version for the `download`, `init`, and `join` commands, e.g., `etcdadm download --version 3.4.1`. You can also find this information in the "help" for each of these commands, e.g., `etcdadm download --help`.
