### ISSUE TITLE
etcdadm only creates cluster with public IP

### ISSUE THREAD

**Issue by sincorchetes** [kubernetes-sigs/etcdadm#208]
VPS Hetzner CentOS 8.
Interfaces:
  - enp7s0, 10.0.0.12
  - ens10, 88.88.88.88 (Public IP)

etcadm deployment:

```
[root@scraper1 etcdadm]# ./etcdadm init --server-cert-extra-sans 10.0.0.12
INFO[0000] [install] extracting etcd archive /var/cache/etcdadm/etcd/v3.4.9/etcd-v3.4.9-linux-amd64.tar.gz to /tmp/etcd680764586 
INFO[0000] [install] verifying etcd 3.4.9 is installed in /opt/bin/ 
INFO[0000] [certificates] creating PKI assets           
INFO[0000] creating a self signed etcd CA certificate and key files 
[certificates] Generated ca certificate and key.
INFO[0000] creating a new server certificate and key files for etcd 
[certificates] Generated server certificate and key.
[certificates] server serving cert is signed for DNS names [example] and IPs [10.0.0.12 88.88.88.88 127.0.0.1]
INFO[0001] creating a new certificate and key files for etcd peering 
[certificates] Generated peer certificate and key.
[certificates] peer serving cert is signed for DNS names [example] and IPs [88.88.88.88]
INFO[0001] creating a new client certificate for the etcdctl 
[certificates] Generated etcdctl-etcd-client certificate and key.
INFO[0001] creating a new client certificate for the apiserver calling etcd 
[certificates] Generated apiserver-etcd-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/etcd/pki"
INFO[0003] [health] Checking local etcd endpoint health 
INFO[0003] [health] Local etcd endpoint is healthy      
INFO[0003] To add another member to the cluster, copy the CA cert/key to its certificate dir and run: 
INFO[0003] 	etcdadm join https://88.88.88.88:2379 
```
How I can deploy etcadm with internal IP instead public?

**Comment by sincorchetes** [comment]
I've solved with this:

```
Here's the part that relate to this issue, to support direct ip assign from flag, or specify interface from flag.

file: apis/config.go

func defaultExternalAddress() (net.IP, error) {
	ip, err := netutil.ResolveBindAddress(net.ParseIP("**0.0.0.0**"))
	if err != nil {
		return nil, fmt.Errorf("failed to find a default external address: %s", err)
	}
	return ip, nil
}
```
#174

**Comment by sincorchetes** [comment]
I've deployed cluster successfully, however, when I try to ask to IP:
```
curl https://10.0.0.12:2379 --insecure
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
```

When I try to add new member:
```
sudo ./etcdadm join https://10.0.0.12:2379
INFO[0000] [certificates] creating PKI assets           
INFO[0000] creating a self signed etcd CA certificate and key files 
[certificates] Using the existing ca certificate and key.
INFO[0000] creating a new server certificate and key files for etcd 
[certificates] Using the existing server certificate and key.
INFO[0000] creating a new certificate and key files for etcd peering 
[certificates] Using the existing peer certificate and key.
INFO[0000] creating a new client certificate for the etcdctl 
[certificates] Using the existing etcdctl-etcd-client certificate and key.
INFO[0000] creating a new client certificate for the apiserver calling etcd 
[certificates] Using the existing apiserver-etcd-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/etcd/pki"
INFO[0001] [membership] Checking if this member was added 
{"level":"warn","ts":"2021-04-27T05:59:02.785+0200","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-9744e0dd-35cc-4842-9b77-20b79e0c3a8c/10.0.0.12:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
FATA[0006] [membership] Error listing members: context deadline exceeded 

```

**Comment by dravenk** [comment]
> I've deployed cluster successfully, however, when I try to ask to IP:
> 
> ```
> curl https://10.0.0.12:2379 --insecure
> curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
> ```
> 
> When I try to add new member:
> 
> ```
> sudo ./etcdadm join https://10.0.0.12:2379
> INFO[0000] [certificates] creating PKI assets           
> INFO[0000] creating a self signed etcd CA certificate and key files 
> [certificates] Using the existing ca certificate and key.
> INFO[0000] creating a new server certificate and key files for etcd 
> [certificates] Using the existing server certificate and key.
> INFO[0000] creating a new certificate and key files for etcd peering 
> [certificates] Using the existing peer certificate and key.
> INFO[0000] creating a new client certificate for the etcdctl 
> [certificates] Using the existing etcdctl-etcd-client certificate and key.
> INFO[0000] creating a new client certificate for the apiserver calling etcd 
> [certificates] Using the existing apiserver-etcd-client certificate and key.
> [certificates] valid certificates and keys now exist in "/etc/etcd/pki"
> INFO[0001] [membership] Checking if this member was added 
> {"level":"warn","ts":"2021-04-27T05:59:02.785+0200","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-9744e0dd-35cc-4842-9b77-20b79e0c3a8c/10.0.0.12:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
> FATA[0006] [membership] Error listing members: context deadline exceeded 
> ```

Adding a node takes two steps, and I encountered the same error when I ignored the first step. So just execute ` rsync -avR /etc/etcd/pki/ca.* <Member IP address>:/ ` in the order described in the documentation to succeed.
https://github.com/kubernetes-sigs/etcdadm#adding-a-member
