### ISSUE TITLE
Use separate tags for etcdadm and etcd-manager using

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/etcdadm#217]
We want to avoid conflict between etcdadm CLI and etcd-manager releases, so let's use separate tags. The kustomize project does this to release various components.

- etcdadm/v0.1.x
- etcd-manager/v3.x.x

## TODO

- [ ] Update the tag regex in the etcdadm staging job spec: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-etcdadm.yaml#L13
- [ ] Similar change for etcd-manager

**Comment by justinsb** [comment]
I did the etcd-manager part of this :-)

It's a little trickier for etcdadm, as it's in the root, so I'm not sure whether we want to give it a prefix (?)
