### ISSUE TITLE
etcd events and main's daily backups are kept for 7 years

### ISSUE THREAD

**Issue by SHreyank4Real** [kubernetes-sigs/etcdadm#280]
https://github.com/kubernetes-sigs/etcdadm/blob/master/etcd-manager/pkg/backupcontroller/cleanup.go

it the document it says etcd events and main's daily backups are kept for 1 year but in the cleanup.go's
line no. 36 default value is `var DailyBackupsRetention = 24 * 7 * 365 * time.Hour.`
which is equal to 7 years 

it should be `var DailyBackupsRetention = 24 * 1 * 365 * time.Hour`. right?

**Comment by justinsb** [comment]
/reopen

Yes - this looks like I made a mistake!

**Comment by SHreyank4Real** [comment]
@justinsb shall I make the changes and raise PR?

**Comment by justinsb** [comment]
Oh that would be great - I'm happy to do so otherwise.

I was thinking 2 years should be a better default - WDYT?

**Comment by SHreyank4Real** [comment]
IMO 1 years is fine.
 
tried creating PR but its failing with lots checks, 
so please do it.
Thank you
