### ISSUE TITLE
[etcd error log] tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by huweihuang** [kubernetes-sigs/etcdadm#340]
I create a new etcd cluster by etcdadm, but the three etcd nodes output the following error logs. 
How to solve this problem？

```
etcd[402254]: {"level":"warn","ts":"2022-08-31T14:17:50.484+0800","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"xxxxx:42176","server-name":"","error":"tls: first record does not look like a TLS handshake"}
```

**Comment by cheese** [comment]
A client from xxxxx:42176 try to access etcd via non-tls connection, for example the HTTP restful gRPC gateway, but etcd is configured to allow only tls access.

**Comment by huweihuang** [comment]
> A client from xxxxx:42176 try to access etcd via non-tls connection, for example the HTTP restful gRPC gateway, but etcd is configured to allow only tls access.

how to fix it?
