### ISSUE TITLE
certificates expiired how do i update ?

### ISSUE THREAD

**Issue by fontexD** [kubernetes-sigs/etcdadm#379]
the certificates on my cluster have expired but i dont see anywhere on how to renew them ? 
i got the ca and key but all the server peer api cert are expired

**Comment by johngmyers** [comment]
Perform a rolling update of the nodes. The expectation is that you would be applying security updates so your nodes wouldn't get that old.

**Comment by fontexD** [comment]
how would a security update on the node update the certificates ? i dont get that
i update my notes every 1 month :))

**Comment by fontexD** [comment]
how do i do this ? i have a 3  nodecluster etcd currently

**Comment by sfxworks** [comment]
etcdadm still needs a way to renew its certs since it holds the key
