### ISSUE TITLE
Plans to archive this repo or reviewing its structure and goal

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/etcdadm#395]
Hi All, as per discussion in the the Apr 2nd SCL office hours about the future of etcdadm we are planning the following actions:

- send out a notice about the intention to archive etcdadm (with emphasis on the CLI)
- start a discussion thread for finding a better home for etcd-manager, first enganging with SIG-etcd and eventually considering alternative options according to the answer we get there

This is a first heads up for user/community that something is probably going to happen down the line, and give room to folks to comment

**Comment by fabriziopandini** [comment]
cc @dlipovetsky @justinsb @vincepri @neolit123

**Comment by neolit123** [comment]
posted on the ML
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/SH463K1CmHs
