### ISSUE TITLE
Support etcd certificate rotation

### ISSUE THREAD

**Issue by sarun87** [kubernetes-sigs/etcdadm#56]
The Peer, Client and Server certs we generate today is valid for *one* year. We will need to run `etcdadm reset` followed by `etcdadm join/init` to create new certs within the given year for the etcd cluster to continue functioning.

Cert rollover needs to be implemented.

**Comment by ambientsound** [comment]
My cluster refuses to start today because the etcd certificates expired. I was looking for some tooling to automatically renew them, but it seems I have to do it manually? This cluster was created using kubeadm.

**Comment by pytimer** [comment]
I send a PR to implement certificates rotation, if someone needs, welcome to review it.
