### ISSUE TITLE
Support tuning configuration

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/etcdadm#62]
The configuration is hard-coded in the [systemd unit file](https://github.com/platform9/etcdadm/blob/8f229f46ec87c46523dd0ac40e9d1d9f2853c71a/constants/constants.go#L84
):
```
LimitNOFILE=65536
Nice=-10
IOSchedulingClass=best-effort
IOSchedulingPriority=2
```
Keep these values as defaults, but make them user-configurable.

See https://coreos.com/etcd/docs/latest/tuning.html

**Comment by pytimer** [comment]
@dlipovetsky I send the PR https://github.com/kubernetes-sigs/etcdadm/pull/121 to implement this issue, could you review it? Thanks.

**Comment by dlipovetsky** [comment]
Is it possible to apply settings across different execution mechanisms (systemd service, container, Pod)? I will report back.
