### ISSUE TITLE
Additional SANs

### ISSUE THREAD

**Issue by alexandrem** [kubernetes-sigs/etcdadm#75]
There doesn't seem to be a configuration available during init/join to add SANs for the generated member server certificate. The pki code currently infers the private ip address from host default interface.

This becomes mandatory if you run the etcd cluster in some cloud private network and you want to expose it to clients that are
- from a different network interface
- using NATed ips (e.g openstack floating ip)

Perhaps it would make more sense to provide this via a local config file and not with additional CLI parameters.

**Comment by dlipovetsky** [comment]
@alexandrem Thanks for raising this!

I think we can support SANs with a flag to begin with. I'll file a separate issue for moving to a config file.

**Comment by pytimer** [comment]
Anyone work on it? If not work, I can take it.
