### ISSUE TITLE
Add flag to specify listening address.

### ISSUE THREAD

**Issue by mauilion** [kubernetes-sigs/etcdadm#77]
This is necessary for environments like Vagrant that have multiple network interfaces.

if I could specify the ip that is used to resolve the external address this would solve this.

**Comment by mauilion** [comment]
I've not. I've seen many cases where advertise and listen addresses are different. 

Listen address sets the IP the etcd will bind to and must be an ip or 0.0.0.0
Advertise is the ip or fqdn that peers or clients will use to address the etcd node. It can be an ip or an fqdn. More important when configuring TLS.

**Comment by dlipovetsky** [comment]
Got it. Then etcdadm should allow the user to specify the listen _and_ advertise addresses.

**Comment by pytimer** [comment]
@dlipovetsky What's progress for this feature, can you tell me, thanks? Now I have user case that one host have multi network interface, one of external address and others are internal address, i need etcd bind one of internal address, this internal address maybe not the default interface.
