### ISSUE TITLE
Update etcd version

### ISSUE THREAD

**Issue by Layshah25** [kubernetes-sigs/etcdadm#82]
How to update etcd form 3.3.8 to 3.3.10 using etcdadm?
Tried updating version in /constants/constants.go and /vendor/github.com/coreos/etcd/version/version.go. Still installing 3.3.8.

**Comment by dlipovetsky** [comment]
We plan to implement an `upgrade` verb to support in-place upgrades.

If you have have a multi-member cluster, you can simulate a rolling in-place upgrade by running
```
etcdadm join --version 3.3.10 <client URL of another member>
```
on each member in sequence.

If you have a single-node cluster, you can take a snapshot, then init from a snapshot, e.g.,
```
etcdctl.sh snapshot save /tmp/etcd.ss
etcdadm init --verson 3.3.10 --snapshot /tmp/etcd.ss
```

(You can also stop the etcd service and replace the binary by hand.)
