### ISSUE TITLE
Client certificate mode

### ISSUE THREAD

**Issue by mattymo** [kubernetes-sigs/etcdadm#85]
It would be great if etcdadm could allow nodes that are not going to be etcd members, but instead clients of etcd to be able to create their own certificates. I think it would add value so that one binary can handle all necessary etcd setup tasks. 

I understand that distributing ca certs to non-etcd nodes is a "bad idea", but configuration management tools could benefit here.

**Comment by dlipovetsky** [comment]
I think being able to generate certs, similar to what `kubeadm init phase certs` does, is a good feature to have.

I also think the CA issue is orthogonal. If the CA is present, etcdadm should use it. But etcdadm should also be able to generate CSRs, and the user can get these signed by an external CA.
