### ISSUE TITLE
make systemd an object

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/etcdadm#99]
*problem*

- Right now we fail somewhat ungracefully if `systemd` isn't available, but it would be nice if we could quickly detect it wasnt there, fail nautrally, or better yet start etcdadm without having systemd at all.  
- If  systemd methods were a  struct,   we could mock them for certain types of tests, which would make those sorts of tests etc platform agnostic.
- it might be nice to make the calling of the systemd functions critical sectionable, i.e. only one call at a time.

*solution* 

pretty easy solution: just wrap the funcs in a struct and init that struct as needed, and have it fail fast if systemd isnt on the host.

*details* 
 
probably want to make this a func inside the constructor:
```
const required_exec = []string("curl","tar","systemctl")
... {
        log.Info("Confirming that executables required for etcadm are on the system")
        // TODO: determine if its possible to run etcdadm in a non-linux environment.
        for _,r := range required_exec {
                path, err := exec.LookPath(r)
                if err != nil {
                        log.Fatal(err)
                        os.Exit(1)
                } else {
                        log.Infof("%v found at %v", r)
                }
        }
}
```

This gives us a way to (1) run on other operating systems (i.e. os x) by mocking it out and (2) give us a clean way of making sure systemd is available / working on the OS when we start.

**Comment by jayunit100** [comment]
i can issue a PR if agreement (assuming probably no debate here, but lmk if anything im missing)

**Comment by pytimer** [comment]
Can we implement systemd package like kubeadm `https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/util/initsystem`, so that we ca adapt to different os, such as Linux, OSX, windows, etc?

**Comment by pytimer** [comment]
@dlipovetsky @jayunit100 I send a PR to implement the init system that adapt different os, if you have time, please review it and if i missing something or wrong, please tell me. Thanks.
